{
  'env': { 'browser': true, 'es2021': true },
  'extends': ['eslint:recommended', 'plugin:react/recommended', 'prettier'],
  'parser': '@babel/eslint-parser',
  'parserOptions':
    {
      'ecmaFeatures': { 'jsx': true },
      'ecmaVersion': 11,
      'requireConfigFile': false,
      'sourceType': 'module',
      'babelOptions': { 'presets': ['@babel/preset-react'] },
    },
  'plugins': ['react', 'prettier'],
  'rules':
    {
      'prettier/prettier':
        ['error', { 'endOfLine': 'auto' }, 'react/prop-types': 0],
    },
}
