install: #установка зависимостей
		npm ci

link: #создание ссылок
		npm link

lint: #запуск линтера
		npx eslint --no-error-on-unmatched-pattern .

lint-fix: #устранение замечаний линтера
		npx eslint --no-error-on-unmatched-pattern --fix .